#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Issues:
# * Capturing errors from client or broker
# * Correct Message body types, use of cproton.Data class?

import sys
from ast import literal_eval
from proton import byte, char, decimal32, decimal64, decimal128, float32, int32, Message, short, symbol, timestamp, ubyte, uint, ulong, ushort
from proton.handlers import MessagingHandler
from proton.reactor import Container
from shim_utils import StrToObj
from struct import unpack
from traceback import format_exc
from uuid import UUID

class Sender(MessagingHandler):
    def __init__(self, url, amqp_type, test_value_list):
        super(Sender, self).__init__()
        self.url = url
        self.amqp_type = amqp_type
        self.test_value_list = test_value_list
        self.sent = 0
        self.confirmed = 0
        self.total = len(test_value_list)

    def on_start(self, event):
        event.container.create_sender(self.url)

    def on_sendable(self, event):
        if self.sent == 0:
            for test_value in self.test_value_list:
                if event.sender.credit:
                    message = self.create_message(test_value)
                    if message is not None:
                        event.sender.send(message)
                        self.sent += 1
                    else:
                        event.connection.close()
                        return

    def create_message(self, test_value):
        # Non-string types using literal_eval
        if self.amqp_type == 'null':
            return Message(id=(self.sent+1), body=None)
        elif self.amqp_type == 'boolean':
            return Message(id=(self.sent+1), body=True if test_value == 'True' else False)
        elif self.amqp_type == 'ubyte':
            return Message(id=(self.sent+1), body=ubyte(literal_eval(test_value)))
        elif self.amqp_type == 'ushort':
            return Message(id=(self.sent+1), body=ushort(literal_eval(test_value)))
        elif self.amqp_type == 'uint':
            return Message(id=(self.sent+1), body=uint(literal_eval(test_value)))
        elif self.amqp_type == 'ulong':
            return Message(id=(self.sent+1), body=ulong(literal_eval(test_value)))
        elif self.amqp_type == 'byte':
            return Message(id=(self.sent+1), body=byte(literal_eval(test_value)))
        elif self.amqp_type == 'short':
            return Message(id=(self.sent+1), body=short(literal_eval(test_value)))
        elif self.amqp_type == 'int':
            return Message(id=(self.sent+1), body=int32(literal_eval(test_value)))
        elif self.amqp_type == 'long':
            return Message(id=(self.sent+1), body=long(literal_eval(test_value)))
        elif self.amqp_type == 'float':
            return Message(id=(self.sent+1), body=float32(unpack('!f', test_value[2:].decode('hex'))[0]))
        elif self.amqp_type == 'double':
            return Message(id=(self.sent+1), body=unpack('!d', test_value[2:].decode('hex'))[0])
        elif self.amqp_type == 'decimal32':
            return Message(id=(self.sent+1), body=decimal32(literal_eval(test_value)))
        elif self.amqp_type == 'decimal64':
            return Message(id=(self.sent+1), body=decimal64(literal_eval(test_value)))
        elif self.amqp_type == 'decimal128':
            return Message(id=(self.sent+1), body=decimal128(test_value.decode('hex')))
        elif self.amqp_type == 'char':
            return Message(id=(self.sent+1), body=char(test_value))
        elif self.amqp_type == 'timestamp':
            return Message(id=(self.sent+1), body=timestamp(literal_eval(test_value)))
        elif self.amqp_type == 'uuid':
            return Message(id=(self.sent+1), body=UUID(test_value))
        elif self.amqp_type == 'binary':
            return Message(id=(self.sent+1), body=bytes(test_value))
        elif self.amqp_type == 'string':
            return Message(id=(self.sent+1), body=unicode(test_value))
        elif self.amqp_type == 'symbol':
            return Message(id=(self.sent+1), body=symbol(test_value))
        elif self.amqp_type == 'list':
            return Message(id=(self.sent+1), body=StrToObj(list(test_value).__iter__()).run())
        elif self.amqp_type == 'map':
            return Message(id=(self.sent+1), body=StrToObj(list(test_value).__iter__()).run())
        else:
            print 'proton-python-send: Unsupported AMQP type "%s"' % self.amqp_type
            return None

    def on_accepted(self, event):
        self.confirmed += 1
        if self.confirmed == self.total:
            event.connection.close()

    def on_disconnected(self, event):
        self.sent = self.confirmed

    @staticmethod
    def _map_string_to_map(str_list):
        return {}

# --- main ---
# Args: 1: Broker address (ip-addr:port)
#       2: Queue name
#       3: AMQP type
#       4...n: Test values as strings
try:
    Container(Sender('%s/%s' % (sys.argv[1], sys.argv[2]), sys.argv[3], sys.argv[4:])).run()
except KeyboardInterrupt:
    pass
except Exception as e:
    print 'proton-python-send EXCEPTION:', e
    print format_exc()
        