#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Issues:
# * Capturing errors from client or broker
# * Correct Message body types, use of cproton.Data class?

import sys
from proton.handlers import MessagingHandler
from proton.reactor import Container
from struct import pack, unpack

class ReceiverError(StandardError):
    def __init__(self, error_message):
        super(ReceiverError, self).__init__(error_message)

class Receiver(MessagingHandler):
    def __init__(self, url, amqp_type, expected_num_messages):
        super(Receiver, self).__init__()
        self.url = url
        self.amqp_type = amqp_type
        self.received_value_list = []
        self.expected = int(expected_num_messages)
        self.received = 0

    def get_received_value_list(self):
        return self.received_value_list

    def on_start(self, event):
        event.container.create_receiver(self.url)

    def on_message(self, event):
        if event.message.id and event.message.id < self.received:
            return # ignore duplicate message
        if self.expected == 0 or self.received < self.expected:
            if self.amqp_type == 'null' or \
               self.amqp_type == 'boolean' or \
               self.amqp_type == 'ubyte' or \
               self.amqp_type == 'ushort' or \
               self.amqp_type == 'uint' or \
               self.amqp_type == 'ulong' or \
               self.amqp_type == 'byte' or \
               self.amqp_type == 'short' or \
               self.amqp_type == 'int' or \
               self.amqp_type == 'long' or \
               self.amqp_type == 'decimal32' or \
               self.amqp_type == 'decimal64' or \
               self.amqp_type == 'decimal128' or \
               self.amqp_type == 'timestamp' or \
               self.amqp_type == 'uuid':
                self.received_value_list.append(str(event.message.body))
            elif self.amqp_type == 'float':
                self.received_value_list.append('0x%08x' % unpack('!L', pack('!f', event.message.body))[0])
            elif self.amqp_type == 'double':
                self.received_value_list.append('0x%016x' % unpack('!Q', pack('!d', event.message.body))[0])
            elif self.amqp_type == 'decimal128':
                self.received_value_list.append(event.message.body.encode('hex'))
            elif self.amqp_type == 'char' or \
                 self.amqp_type == 'binary' or \
                 self.amqp_type == 'string' or \
                 self.amqp_type == 'symbol':
                self.received_value_list.append(event.message.body)
            elif self.amqp_type == 'list' or \
                 self.amqp_type == 'map':
                self.received_value_list.append(event.message.body)
            else:
                print 'proton-python-receive: Unsupported AMQP type "%s"' % self.amqp_type
                return
            self.received += 1
            if self.received == self.expected:
                event.receiver.close()
                event.connection.close()

# --- main ---
# Args: 1: Broker address (ip-addr:port)
#       2: Queue name
#       3: AMQP type
#       4: Expected number of test values to receive
try:
    rcv = Receiver('%s/%s' % (sys.argv[1], sys.argv[2]), sys.argv[3], sys.argv[4])
    Container(rcv).run()
    print sys.argv[3]
    for val in rcv.get_received_value_list():
        print val
except KeyboardInterrupt:
    pass
except Exception as e:
    print 'proton-python-receive EXCEPTION:', e

