[package]
name = "amqp_types_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
fe2o3-amqp = "0.0.21"
anyhow = "1"
ordered-float = "3"
hex = "0.4"
uuid = "1"
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread", "rt"]}