[package]
name = "amqp_types_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "Sender"
path = "src/bin/sender.rs"

[[bin]]
name = "Receiver"
path = "src/bin/receiver.rs"

[dependencies]
serde_json = "1"
fe2o3-amqp = "0.0.17"
anyhow = "1"
ordered-float = "3"
hex = "0.4"
uuid = "1"